[tool.black]
line-length = 120
target-version = ['py313']
skip-string-normalization = true
safe = true
workers = 2
verbose = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''